# Generated by Django 3.1.1 on 2020-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmaDonate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nid', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=2083)),
                ('image', models.ImageField(upload_to='covid_neg_report')),
            ],
        ),
        migrations.CreateModel(
            name='PlasmaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nid', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=2083)),
                ('image', models.ImageField(upload_to='covid_pos_report')),
            ],
        ),
    ]
