# Generated by Django 3.1.1 on 2020-09-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('story', models.CharField(max_length=1000)),
            ],
        ),
    ]
