# Generated by Django 3.1.1 on 2020-09-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='singleBlog',
        ),
    ]
