# Generated by Django 3.1.1 on 2020-09-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200926_0231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='singleBlog',
            new_name='Blog',
        ),
    ]
