# Generated by Django 3.1.1 on 2020-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultWithDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('nid', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
            ],
        ),
    ]
