# Generated by Django 3.1.1 on 2020-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAmbulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=30)),
                ('ambulance_type', models.CharField(max_length=20)),
                ('ambulance_number', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=254)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ReserveAmbulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('hospital_name', models.CharField(max_length=30)),
                ('ambulance_type', models.CharField(max_length=20)),
                ('ambulance_number', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('patient_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('blood_type', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('nid', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('bkash_number', models.CharField(max_length=15)),
                ('bkash_transaction_id', models.CharField(max_length=20)),
            ],
        ),
    ]
