# Generated by Django 3.1.1 on 2020-09-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_service_provider', '0002_availableoxygencylinder_reserveoxygencylinder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveoxygencylinder',
            old_name='ambulance_number',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='reserveoxygencylinder',
            old_name='hospital_name',
            new_name='cylinder_number',
        ),
        migrations.RenameField(
            model_name='reserveoxygencylinder',
            old_name='ambulance_type',
            new_name='cylinder_size',
        ),
    ]
